services:
  paddleocr:
    build: .
    expose:
      - "8001"

    volumes:
      - ./models:/root/.paddlex
      
    networks:
      - ocr-internal

    restart: unless-stopped
    
networks:
  ocr-internal:
    external: true
