services:
  paddleocr:
    build: .
    expose:
      - "8001"

    volumes:
      - ./models:/root/.paddlex
      
    networks:
      - demo-projects_network

    restart: unless-stopped
    
networks:
  demo-projects_network:
    external: true